package com.demo.ar.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.demo.ar.model.User;
import com.demo.ar.repository.UserRepository;

@Controller // This means that this class is a Controller
public class MainController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setUsername(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@RequestMapping(path = "/home")
	public String Home() {
		// This returns a JSON or XML with the users
		return "home.jsp";
	}

	@RequestMapping(path = "/login")
	public String Login() {
		// This returns a JSON or XML with the users
		return "login.jsp";
	}

	@RequestMapping(path = "/logout-success")
	public String LogOut() {
		// This returns a JSON or XML with the users
		return "logout.jsp";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@RequestMapping(value = "/user")
	public Principal user(Principal principal) {
		return principal;
	}
}
